language: python
sudo: false
python:
- 2.7
install:
- pip install pytest pytest-cov coveralls flake8
- pip install git+https://github.com/dittos/graphql-py.git # Last version of graphql-py
script:
- py.test --cov=graphql_relay
# - flake8
after_success:
- coveralls
