language: python
dist: xenial

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy3
install:
  - pip install pytest pytest-cov flake8
  - pip install .
script:
  - py.test --cov=graphql_relay
# - flake8
after_success:
  - pip install coveralls
  - coveralls
