language: python
matrix:
  include:
    - name: Code quality tests
      env: TOXENV=flake8,mypy
      python: 3.7
      dist: xenial
      sudo: true
    - name: Unit tests with Python 3.8
      env: TOXENV=py38
      python: 3.8
      dist: xenial
      sudo: true
    - name: Unit tests with Python 3.7
      env: TOXENV=py37
      python: 3.7
      dist: xenial
      sudo: true
    - name: Unit tests with Python 3.6
      env: TOXENV=py36
      python: 3.6
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$TRAVIS_BUILD_DIR/.tox"
install:
  - pip install "poetry>=1.0.0"
  - poetry install
script:
  - tox -e $TOXENV -- --cov-report term-missing --cov=graphql_relay
after_success:
  - codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
    python: 3.7
  skip_existing: true
  username: mvanlonden
  password:
    secure: gu79sV5e3wkUI8eH20TbBRctOOGkuWe6EQUjJP17q1Jm15/sJsehOaaLPiG0psxtqBGABp+z+xXkjhRfNMowY2xJPLjGmpF23pOIWGjBWKLKXzJStegKM6kwJYyHzcykIhBEb74047FhqhcwOgZcsp6sZpfzuby+onevLzPDI0C4jTARw7WAqMln9JIBZJyoQKp9fpr8AoXL2JtHr6sjkeJ94lz1XViL9rtTo7qFYfqYS3XdKO0wJhLfMUXSihIzSWQykBVv+75tMKQr0CtGALXcJSRGT6Sb31GiFyG93rtcOcBvbjFt1MK8aNKyIMhwgSqjcgKvxWAvXn4MsCaabHPVEv0YuT9t9cQzaAvi81LqHkpALgpDfXFfsMzHG18/8ME9TpM8u52r/ST5lhukglfnxWVy4hg8VLZ0iiTtpS3hx1Ba4Uecr++6fI5X+KL3EPabApQM+t4rcC0h4mEbjq3IkZ/ANAIJ2UjKTMcUkbQbKqJ1MY4xQyw+vVugffBmhEWSb4GnQPEadMGD6qfUI+t7epDP0ipp67rOiUooFYGabQp40pf7MxFPG23fvJ3JWbo3fzcIRmQiSalrIL1gFXH2DQnv4xhZvwnci+dIK29mamH0CfmjAJ8BdfzRsjV156BZbfkzXRfWDMes9G2E8S27xJJ2N4ySNIMkaXsu1u4=
