language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
install:
- pip install pytest pytest-cov coveralls flake8
- pip install graphql-core==0.1a0
- python setup.py develop
script:
- py.test --cov=graphql_relay
# - flake8
after_success:
- coveralls
