language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypy
install:
- pip install pytest pytest-cov coveralls flake8
- pip install https://github.com/graphql-python/graphql-core/archive/master.zip
script:
- py.test --cov=graphql_relay
# - flake8
after_success:
- coveralls
