language: python
matrix:
  include:
    - env: TOXENV=flake8,mypy
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOXENV=py37
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOXENV=py36
      python: 3.6
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$TRAVIS_BUILD_DIR/.tox"
install:
  - pip install "poetry>=0.12.16"
  - poetry install
script:
  - tox -e $TOXENV -- --cov-report term-missing --cov=src
after_success:
  - codecov
deploy:
  provider: pypi
  user: mvanlonden
  on:
    tags: true
    branch: next
  password:
    secure: XVtT4qW+ghIAD+ebcJQQd4WQtFCbXy/9EQen2CehP1UBB/9uIzWRxeJmuB5FKDUCsWt9LZmMPZvvBD6iQeQSO1hSue1gE7kCiaBLf65z/MkX1AvrSGgXUxxUIHAvMjI4ZQ1EnwnPLvBKU2LB7puYETCruMFx13f7VXGklQwdUYvOWWML8fNg99vdqxkteYMHPQJ5t4MLwFSrmnh9o1kmqYb9Le2/o5vHNVj/x4St0LFa7m9PMsiCqfKCf3zqbpV8dnTTWDPZKtfr50ptslrp1CvnYLiu7aXe0PQxkjVVxNLuMJLUlk+oPOWuuRZon1eAgm0XGHJF7WeVt9I5CCA+x1dZ7KsPVZnOZ261yutAUKuyV+XAPqtGwNOyUTLOM3ZgcnrSK4fyxG8AuTEX8uj+3Byms10V/ZJ+ViG0VJLD3hzcqIsxm6PjnN4gE+6HWQSf4oWLVkp851SLsgF45OO2nPh/zw9dcYWOIZFmyG931mUnUBmR+m8CztbASAyIt0Q/0TjXbpS06XM308oPMyo5SV23QBMG/f+pYOSDqVa9ZOOxU9oF6ezNu3fTpfuG/OqfyO9+X94UT+0q6lLMUf3q3xBM07fNrs8AOq1j3UiUPBlhBqtghuuZM4L5ULvZ20ypt0Ifj46IVV6n7eRiG8quX/M2YkrIAwO2ONgJnZLCbUs=
