language: python
matrix:
  include:
    - env: TOXENV=flake8,mypy
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOXENV=py37
      python: 3.7
      dist: xenial
      sudo: true
    - env: TOXENV=py36
      python: 3.6
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$TRAVIS_BUILD_DIR/.tox"
install:
  - pip install "poetry>=0.12.16"
  - poetry install
script:
  - tox -e $TOXENV -- --cov-report term-missing --cov=src
after_success:
  - codecov
deploy:
  provider: pypi
  on:
    tags: true
    branch: next
